manifest:
  remotes:
    - name: urob
      url-base: https://github.com/urob
    - name: m165437   
      url-base: https://github.com/M165437
  projects:
    - name: zmk
      remote: urob
      revision: main
      import: app/west.yml
    - name: nice-view-gem #new entry
      remote: m165437 #new entry
      revision: main #new entry
  self:
    path: config
